adding a list of comments to singleReview page
kyrikoni/kk-frontend-portfolio-project pull request #3
Opened 2023-01-10 16:19 UTC by kyrikoni

2023-01-10 16:42 UTC, B7Bprog requested changes
Hey Kyri, please see my comments, amend your code and then feel free to merge it.

2023-01-10 16:42 UTC, B7Bprog commented on src/api.js
> +    console.log(res.data.comments);
Please remove logs.

2023-01-10 16:42 UTC, B7Bprog commented on src/components/Comments.jsx
> +      setComments(comments);
Please use a 'loading' state to give a visual feedback of loading comments to the user.

2023-01-11 09:25 UTC, Pipe-Smoking-Rabbit approved these changes
Small feedback on slack, otherwise good to merge!

2023-01-11 09:54 UTC, merged